name: Convert Jupyter Notebook

on:
  push:
    branches:
    - main
    paths:
    - 'notebooks/NeonDisco-FT-Analysis.ipynb'

jobs:
  release:
    if: github.actor == 'sufyazi'
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies & Convert NeonDisco-FT-Analysis.ipynb
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        jupyter nbconvert --to html --template=pj notebooks/NeonDisco-FT-Analysis.ipynb

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add notebooks/NeonDisco-FT-Analysis.html
        git commit -m "Convert Jupyter Notebook to HTML" -a

    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
